package miage.nanterre.m1app.realtimekeynote.Enum;

public enum SeanceAnalyticsEnum {
    MONTHS,
    ATTENTION_AVG_PER_MONTH,
    ATTENTION_DIFF_PER_MONTH,
    ABSENT_AVG_PER_MONTH,
    ATTENTION_AVG,
    ATTENTION_MAX,
    ATTENTION_MIN,
    OBSERVED_PARTICIPANTS,
    ABSENT_PARTICIPANTS,
    SESSION,
    SESSION_ANALYTICS_DATA,
    DATA,
    LABEL;
}
